/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.bigdata.ml.entity;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SalesPurchasing extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SalesPurchasing\",\"namespace\":\"com.bigdata.ml.entity\",\"fields\":[{\"name\":\"product_id\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"product_name\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"price\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"category\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"product_info\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"product_infoik\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"product_contacts\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"contact_phone\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"company_name\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"address\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"specification\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"quantity\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"packing\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"creator_user\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"direction\",\"type\":\"string\",\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence product_id;
  @Deprecated public java.lang.CharSequence product_name;
  @Deprecated public java.lang.CharSequence price;
  @Deprecated public java.lang.CharSequence category;
  @Deprecated public java.lang.CharSequence product_info;
  @Deprecated public java.lang.CharSequence product_infoik;
  @Deprecated public java.lang.CharSequence product_contacts;
  @Deprecated public java.lang.CharSequence contact_phone;
  @Deprecated public java.lang.CharSequence company_name;
  @Deprecated public java.lang.CharSequence address;
  @Deprecated public java.lang.CharSequence specification;
  @Deprecated public java.lang.CharSequence quantity;
  @Deprecated public java.lang.CharSequence packing;
  @Deprecated public java.lang.CharSequence creator_user;
  @Deprecated public java.lang.CharSequence direction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SalesPurchasing() {}

  /**
   * All-args constructor.
   */
  public SalesPurchasing(java.lang.CharSequence product_id, java.lang.CharSequence product_name, java.lang.CharSequence price, java.lang.CharSequence category, java.lang.CharSequence product_info, java.lang.CharSequence product_infoik, java.lang.CharSequence product_contacts, java.lang.CharSequence contact_phone, java.lang.CharSequence company_name, java.lang.CharSequence address, java.lang.CharSequence specification, java.lang.CharSequence quantity, java.lang.CharSequence packing, java.lang.CharSequence creator_user, java.lang.CharSequence direction) {
    this.product_id = product_id;
    this.product_name = product_name;
    this.price = price;
    this.category = category;
    this.product_info = product_info;
    this.product_infoik = product_infoik;
    this.product_contacts = product_contacts;
    this.contact_phone = contact_phone;
    this.company_name = company_name;
    this.address = address;
    this.specification = specification;
    this.quantity = quantity;
    this.packing = packing;
    this.creator_user = creator_user;
    this.direction = direction;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_id;
    case 1: return product_name;
    case 2: return price;
    case 3: return category;
    case 4: return product_info;
    case 5: return product_infoik;
    case 6: return product_contacts;
    case 7: return contact_phone;
    case 8: return company_name;
    case 9: return address;
    case 10: return specification;
    case 11: return quantity;
    case 12: return packing;
    case 13: return creator_user;
    case 14: return direction;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_id = (java.lang.CharSequence)value$; break;
    case 1: product_name = (java.lang.CharSequence)value$; break;
    case 2: price = (java.lang.CharSequence)value$; break;
    case 3: category = (java.lang.CharSequence)value$; break;
    case 4: product_info = (java.lang.CharSequence)value$; break;
    case 5: product_infoik = (java.lang.CharSequence)value$; break;
    case 6: product_contacts = (java.lang.CharSequence)value$; break;
    case 7: contact_phone = (java.lang.CharSequence)value$; break;
    case 8: company_name = (java.lang.CharSequence)value$; break;
    case 9: address = (java.lang.CharSequence)value$; break;
    case 10: specification = (java.lang.CharSequence)value$; break;
    case 11: quantity = (java.lang.CharSequence)value$; break;
    case 12: packing = (java.lang.CharSequence)value$; break;
    case 13: creator_user = (java.lang.CharSequence)value$; break;
    case 14: direction = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'product_id' field.
   */
  public java.lang.CharSequence getProductId() {
    return product_id;
  }

  /**
   * Sets the value of the 'product_id' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.product_id = value;
  }

  /**
   * Gets the value of the 'product_name' field.
   */
  public java.lang.CharSequence getProductName() {
    return product_name;
  }

  /**
   * Sets the value of the 'product_name' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.CharSequence getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.CharSequence value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }

  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'product_info' field.
   */
  public java.lang.CharSequence getProductInfo() {
    return product_info;
  }

  /**
   * Sets the value of the 'product_info' field.
   * @param value the value to set.
   */
  public void setProductInfo(java.lang.CharSequence value) {
    this.product_info = value;
  }

  /**
   * Gets the value of the 'product_infoik' field.
   */
  public java.lang.CharSequence getProductInfoik() {
    return product_infoik;
  }

  /**
   * Sets the value of the 'product_infoik' field.
   * @param value the value to set.
   */
  public void setProductInfoik(java.lang.CharSequence value) {
    this.product_infoik = value;
  }

  /**
   * Gets the value of the 'product_contacts' field.
   */
  public java.lang.CharSequence getProductContacts() {
    return product_contacts;
  }

  /**
   * Sets the value of the 'product_contacts' field.
   * @param value the value to set.
   */
  public void setProductContacts(java.lang.CharSequence value) {
    this.product_contacts = value;
  }

  /**
   * Gets the value of the 'contact_phone' field.
   */
  public java.lang.CharSequence getContactPhone() {
    return contact_phone;
  }

  /**
   * Sets the value of the 'contact_phone' field.
   * @param value the value to set.
   */
  public void setContactPhone(java.lang.CharSequence value) {
    this.contact_phone = value;
  }

  /**
   * Gets the value of the 'company_name' field.
   */
  public java.lang.CharSequence getCompanyName() {
    return company_name;
  }

  /**
   * Sets the value of the 'company_name' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.company_name = value;
  }

  /**
   * Gets the value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'specification' field.
   */
  public java.lang.CharSequence getSpecification() {
    return specification;
  }

  /**
   * Sets the value of the 'specification' field.
   * @param value the value to set.
   */
  public void setSpecification(java.lang.CharSequence value) {
    this.specification = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   */
  public java.lang.CharSequence getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.CharSequence value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'packing' field.
   */
  public java.lang.CharSequence getPacking() {
    return packing;
  }

  /**
   * Sets the value of the 'packing' field.
   * @param value the value to set.
   */
  public void setPacking(java.lang.CharSequence value) {
    this.packing = value;
  }

  /**
   * Gets the value of the 'creator_user' field.
   */
  public java.lang.CharSequence getCreatorUser() {
    return creator_user;
  }

  /**
   * Sets the value of the 'creator_user' field.
   * @param value the value to set.
   */
  public void setCreatorUser(java.lang.CharSequence value) {
    this.creator_user = value;
  }

  /**
   * Gets the value of the 'direction' field.
   */
  public java.lang.CharSequence getDirection() {
    return direction;
  }

  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(java.lang.CharSequence value) {
    this.direction = value;
  }

  /** Creates a new SalesPurchasing RecordBuilder */
  public static com.bigdata.ml.entity.SalesPurchasing.Builder newBuilder() {
    return new com.bigdata.ml.entity.SalesPurchasing.Builder();
  }
  
  /** Creates a new SalesPurchasing RecordBuilder by copying an existing Builder */
  public static com.bigdata.ml.entity.SalesPurchasing.Builder newBuilder(com.bigdata.ml.entity.SalesPurchasing.Builder other) {
    return new com.bigdata.ml.entity.SalesPurchasing.Builder(other);
  }
  
  /** Creates a new SalesPurchasing RecordBuilder by copying an existing SalesPurchasing instance */
  public static com.bigdata.ml.entity.SalesPurchasing.Builder newBuilder(com.bigdata.ml.entity.SalesPurchasing other) {
    return new com.bigdata.ml.entity.SalesPurchasing.Builder(other);
  }
  
  /**
   * RecordBuilder for SalesPurchasing instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SalesPurchasing>
    implements org.apache.avro.data.RecordBuilder<SalesPurchasing> {

    private java.lang.CharSequence product_id;
    private java.lang.CharSequence product_name;
    private java.lang.CharSequence price;
    private java.lang.CharSequence category;
    private java.lang.CharSequence product_info;
    private java.lang.CharSequence product_infoik;
    private java.lang.CharSequence product_contacts;
    private java.lang.CharSequence contact_phone;
    private java.lang.CharSequence company_name;
    private java.lang.CharSequence address;
    private java.lang.CharSequence specification;
    private java.lang.CharSequence quantity;
    private java.lang.CharSequence packing;
    private java.lang.CharSequence creator_user;
    private java.lang.CharSequence direction;

    /** Creates a new Builder */
    private Builder() {
      super(com.bigdata.ml.entity.SalesPurchasing.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.bigdata.ml.entity.SalesPurchasing.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.category)) {
        this.category = data().deepCopy(fields()[3].schema(), other.category);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.product_info)) {
        this.product_info = data().deepCopy(fields()[4].schema(), other.product_info);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.product_infoik)) {
        this.product_infoik = data().deepCopy(fields()[5].schema(), other.product_infoik);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.product_contacts)) {
        this.product_contacts = data().deepCopy(fields()[6].schema(), other.product_contacts);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.contact_phone)) {
        this.contact_phone = data().deepCopy(fields()[7].schema(), other.contact_phone);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.company_name)) {
        this.company_name = data().deepCopy(fields()[8].schema(), other.company_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address)) {
        this.address = data().deepCopy(fields()[9].schema(), other.address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.specification)) {
        this.specification = data().deepCopy(fields()[10].schema(), other.specification);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.quantity)) {
        this.quantity = data().deepCopy(fields()[11].schema(), other.quantity);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.packing)) {
        this.packing = data().deepCopy(fields()[12].schema(), other.packing);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.creator_user)) {
        this.creator_user = data().deepCopy(fields()[13].schema(), other.creator_user);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.direction)) {
        this.direction = data().deepCopy(fields()[14].schema(), other.direction);
        fieldSetFlags()[14] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SalesPurchasing instance */
    private Builder(com.bigdata.ml.entity.SalesPurchasing other) {
            super(com.bigdata.ml.entity.SalesPurchasing.SCHEMA$);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.category)) {
        this.category = data().deepCopy(fields()[3].schema(), other.category);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.product_info)) {
        this.product_info = data().deepCopy(fields()[4].schema(), other.product_info);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.product_infoik)) {
        this.product_infoik = data().deepCopy(fields()[5].schema(), other.product_infoik);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.product_contacts)) {
        this.product_contacts = data().deepCopy(fields()[6].schema(), other.product_contacts);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.contact_phone)) {
        this.contact_phone = data().deepCopy(fields()[7].schema(), other.contact_phone);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.company_name)) {
        this.company_name = data().deepCopy(fields()[8].schema(), other.company_name);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address)) {
        this.address = data().deepCopy(fields()[9].schema(), other.address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.specification)) {
        this.specification = data().deepCopy(fields()[10].schema(), other.specification);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.quantity)) {
        this.quantity = data().deepCopy(fields()[11].schema(), other.quantity);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.packing)) {
        this.packing = data().deepCopy(fields()[12].schema(), other.packing);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.creator_user)) {
        this.creator_user = data().deepCopy(fields()[13].schema(), other.creator_user);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.direction)) {
        this.direction = data().deepCopy(fields()[14].schema(), other.direction);
        fieldSetFlags()[14] = true;
      }
    }

    /** Gets the value of the 'product_id' field */
    public java.lang.CharSequence getProductId() {
      return product_id;
    }
    
    /** Sets the value of the 'product_id' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.product_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'product_id' field has been set */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'product_id' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearProductId() {
      product_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'product_name' field */
    public java.lang.CharSequence getProductName() {
      return product_name;
    }
    
    /** Sets the value of the 'product_name' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.product_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'product_name' field has been set */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'product_name' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.CharSequence getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setPrice(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'price' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearPrice() {
      price = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'category' field */
    public java.lang.CharSequence getCategory() {
      return category;
    }
    
    /** Sets the value of the 'category' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.category = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'category' field has been set */
    public boolean hasCategory() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'category' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearCategory() {
      category = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'product_info' field */
    public java.lang.CharSequence getProductInfo() {
      return product_info;
    }
    
    /** Sets the value of the 'product_info' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setProductInfo(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.product_info = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'product_info' field has been set */
    public boolean hasProductInfo() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'product_info' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearProductInfo() {
      product_info = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'product_infoik' field */
    public java.lang.CharSequence getProductInfoik() {
      return product_infoik;
    }
    
    /** Sets the value of the 'product_infoik' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setProductInfoik(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.product_infoik = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'product_infoik' field has been set */
    public boolean hasProductInfoik() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'product_infoik' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearProductInfoik() {
      product_infoik = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'product_contacts' field */
    public java.lang.CharSequence getProductContacts() {
      return product_contacts;
    }
    
    /** Sets the value of the 'product_contacts' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setProductContacts(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.product_contacts = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'product_contacts' field has been set */
    public boolean hasProductContacts() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'product_contacts' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearProductContacts() {
      product_contacts = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'contact_phone' field */
    public java.lang.CharSequence getContactPhone() {
      return contact_phone;
    }
    
    /** Sets the value of the 'contact_phone' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setContactPhone(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.contact_phone = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'contact_phone' field has been set */
    public boolean hasContactPhone() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'contact_phone' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearContactPhone() {
      contact_phone = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'company_name' field */
    public java.lang.CharSequence getCompanyName() {
      return company_name;
    }
    
    /** Sets the value of the 'company_name' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.company_name = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'company_name' field has been set */
    public boolean hasCompanyName() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'company_name' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearCompanyName() {
      company_name = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.address = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'address' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearAddress() {
      address = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'specification' field */
    public java.lang.CharSequence getSpecification() {
      return specification;
    }
    
    /** Sets the value of the 'specification' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setSpecification(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.specification = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'specification' field has been set */
    public boolean hasSpecification() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'specification' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearSpecification() {
      specification = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'quantity' field */
    public java.lang.CharSequence getQuantity() {
      return quantity;
    }
    
    /** Sets the value of the 'quantity' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setQuantity(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.quantity = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'quantity' field has been set */
    public boolean hasQuantity() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'quantity' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearQuantity() {
      quantity = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'packing' field */
    public java.lang.CharSequence getPacking() {
      return packing;
    }
    
    /** Sets the value of the 'packing' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setPacking(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.packing = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'packing' field has been set */
    public boolean hasPacking() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'packing' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearPacking() {
      packing = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'creator_user' field */
    public java.lang.CharSequence getCreatorUser() {
      return creator_user;
    }
    
    /** Sets the value of the 'creator_user' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setCreatorUser(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.creator_user = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'creator_user' field has been set */
    public boolean hasCreatorUser() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'creator_user' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearCreatorUser() {
      creator_user = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'direction' field */
    public java.lang.CharSequence getDirection() {
      return direction;
    }
    
    /** Sets the value of the 'direction' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder setDirection(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.direction = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'direction' field has been set */
    public boolean hasDirection() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'direction' field */
    public com.bigdata.ml.entity.SalesPurchasing.Builder clearDirection() {
      direction = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public SalesPurchasing build() {
      try {
        SalesPurchasing record = new SalesPurchasing();
        record.product_id = fieldSetFlags()[0] ? this.product_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.product_name = fieldSetFlags()[1] ? this.product_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.category = fieldSetFlags()[3] ? this.category : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.product_info = fieldSetFlags()[4] ? this.product_info : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.product_infoik = fieldSetFlags()[5] ? this.product_infoik : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.product_contacts = fieldSetFlags()[6] ? this.product_contacts : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.contact_phone = fieldSetFlags()[7] ? this.contact_phone : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.company_name = fieldSetFlags()[8] ? this.company_name : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.address = fieldSetFlags()[9] ? this.address : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.specification = fieldSetFlags()[10] ? this.specification : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.quantity = fieldSetFlags()[11] ? this.quantity : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.packing = fieldSetFlags()[12] ? this.packing : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.creator_user = fieldSetFlags()[13] ? this.creator_user : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.direction = fieldSetFlags()[14] ? this.direction : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
